name: Deploy

# Trigger the workflow on push on the master branch
on:
  push:
    branches:
      - master

# Authenticate to the server via ssh and run our deployment script
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      # Step 3: Install PHP dependencies
      - name: Install Composer dependencies
        run: composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

      # Step 4: Set up Node.js and Install Dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install npm dependencies
        run: npm install

      # Step 5: Build assets
      - name: Build assets
        run: npm run build

      # Step 6: Upload built assets as an artifact
      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: built-assets
          path: public
          retention-days: 1
  deploy:
    name: Deploy to Server
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Download built assets
      - name: Download assets
        uses: actions/download-artifact@v4
        with:
          name: built-assets

      # Step 3: Deploy to the server
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: |
            set -e
            echo "Deploying application..."

            # Navigate to the application directory
            cd /web/mat-et-lili

            # Update the repository
            git pull origin production

            # Replace public assets with built assets
            rsync -r --delete public/ /web/mat-et-lili/public/

            # Install PHP dependencies
            composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

            # Run Laravel commands
            php artisan down
            php artisan migrate --force
            php artisan optimize
            php artisan up

            echo "Deployment completed successfully!"
